/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ListaController;
import Modelo.Turno0;
import java.awt.TextArea;

/**
 *
 * @author adrie
 */
public class VistaFormulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaFormulario.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public VistaFormulario(Turno0 turno, ListaController controller) {
        initComponents();
        precargarDatos(turno);
    }

    private VistaFormulario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoDNI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CampoObraSocial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoMotivo = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 70, 77));

        jPanel2.setBackground(new java.awt.Color(169, 186, 169));
        jPanel2.setFocusable(false);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        CampoNombre.setBackground(new java.awt.Color(255, 255, 255));
        CampoNombre.setForeground(new java.awt.Color(153, 153, 153));
        CampoNombre.setText("Ingrese el nombre del paciente");
        CampoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoNombreFocusLost(evt);
            }
        });
        CampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido:");

        CampoApellido.setBackground(new java.awt.Color(255, 255, 255));
        CampoApellido.setForeground(new java.awt.Color(153, 153, 153));
        CampoApellido.setText("Ingrese el apellido del paciente");
        CampoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoApellidoFocusLost(evt);
            }
        });
        CampoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoApellidoActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DNI:");

        CampoDNI.setBackground(new java.awt.Color(255, 255, 255));
        CampoDNI.setForeground(new java.awt.Color(153, 153, 153));
        CampoDNI.setText("Ingrese el DNI del paciente");
        CampoDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoDNIFocusLost(evt);
            }
        });
        CampoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDNIActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono:");

        CampoTelefono.setBackground(new java.awt.Color(255, 255, 255));
        CampoTelefono.setForeground(new java.awt.Color(153, 153, 153));
        CampoTelefono.setText("Ingrese el telefono del paciente");
        CampoTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoTelefonoFocusLost(evt);
            }
        });
        CampoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefonoActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Obra social:");

        CampoObraSocial.setBackground(new java.awt.Color(255, 255, 255));
        CampoObraSocial.setForeground(new java.awt.Color(153, 153, 153));
        CampoObraSocial.setText("Ingrese la obra social del paciente");
        CampoObraSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoObraSocialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoObraSocialFocusLost(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Motivo de consulta:");

        CampoMotivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoMotivoFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(CampoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(CampoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addComponent(CampoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addComponent(CampoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5))
                    .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(135, 174, 174));
        jLabel1.setText("Ingrese los datos del paciente ");

        BotonGuardar.setBackground(new java.awt.Color(169, 186, 169));
        BotonGuardar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(51, 51, 51));
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonAtras.setBackground(new java.awt.Color(169, 186, 169));
        BotonAtras.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BotonAtras.setForeground(new java.awt.Color(0, 51, 51));
        BotonAtras.setText("Atras");

        BotonCancelar.setBackground(new java.awt.Color(169, 186, 169));
        BotonCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BotonCancelar.setForeground(new java.awt.Color(51, 51, 51));
        BotonCancelar.setText("cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotonAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BotonAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNombreFocusGained
        if (CampoNombre.getText().equals("Ingrese el nombre del paciente")) {
            CampoNombre.setText("");
            CampoNombre.setForeground(new java.awt.Color(0, 0, 0)); // <- Texto de usuario en NEGRO
        }
    }//GEN-LAST:event_CampoNombreFocusGained

    private void CampoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNombreFocusLost
        if (CampoNombre.getText().isEmpty()) {
            CampoNombre.setText("Ingrese el nombre del paciente");
            CampoNombre.setForeground(new java.awt.Color(153, 153, 153)); // <- Placeholder en GRIS
        }
    }//GEN-LAST:event_CampoNombreFocusLost

    private void CampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreActionPerformed

    private void CampoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoApellidoFocusGained
        if (CampoApellido.getText().equals("Ingrese el apellido del paciente")) {
            CampoApellido.setText("");
            CampoApellido.setForeground(new java.awt.Color(0, 0, 0)); // <- Texto de usuario en NEGRO
        }
    }//GEN-LAST:event_CampoApellidoFocusGained

    private void CampoApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoApellidoFocusLost
        if (CampoApellido.getText().isEmpty()) {
            CampoApellido.setText("Ingrese el apellido del paciente");
            CampoApellido.setForeground(new java.awt.Color(153, 153, 153)); // <- Placeholder en GRIS
        }
    }//GEN-LAST:event_CampoApellidoFocusLost

    private void CampoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoApellidoActionPerformed

    private void CampoDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoDNIFocusGained

        if (CampoDNI.getText().equals("Ingrese el DNI del paciente")) {
            CampoDNI.setText("");
            CampoDNI.setForeground(new java.awt.Color(0, 0, 0)); // Color de texto normal (gris)
        }
    }//GEN-LAST:event_CampoDNIFocusGained

    private void CampoDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoDNIFocusLost
        if (CampoDNI.getText().isEmpty()) {
            CampoDNI.setText("Ingrese el DNI del paciente");
            CampoDNI.setForeground(new java.awt.Color(153, 153, 153)); // Color de sugerencia (gris)
        }
    }//GEN-LAST:event_CampoDNIFocusLost

    private void CampoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDNIActionPerformed

    private void CampoTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoTelefonoFocusGained
        if (CampoTelefono.getText().equals("Ingrese el telefono del paciente")) {
            CampoTelefono.setText("");
            CampoTelefono.setForeground(new java.awt.Color(0, 0, 0)); // Color de texto normal (gris)
        }
    }//GEN-LAST:event_CampoTelefonoFocusGained

    private void CampoTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoTelefonoFocusLost
        if (CampoTelefono.getText().isEmpty()) {
            CampoTelefono.setText("Ingrese el telefono del paciente");
            CampoTelefono.setForeground(new java.awt.Color(153, 153, 153)); // Color de sugerencia (gris)
        }
    }//GEN-LAST:event_CampoTelefonoFocusLost

    private void CampoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefonoActionPerformed

    private void CampoObraSocialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoObraSocialFocusGained
        if (CampoObraSocial.getText().equals("Ingrese la obra social del paciente")) {
            CampoObraSocial.setText("");
            CampoObraSocial.setForeground(new java.awt.Color(0, 0, 0)); // Color de texto normal (gris)
        }
    }//GEN-LAST:event_CampoObraSocialFocusGained

    private void CampoObraSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoObraSocialFocusLost
        if (CampoObraSocial.getText().isEmpty()) {
            CampoObraSocial.setText("Ingrese la obra social del paciente");
            CampoObraSocial.setForeground(new java.awt.Color(153, 153, 153)); // Color de sugerencia (gris)

        }
    }//GEN-LAST:event_CampoObraSocialFocusLost

    private void CampoMotivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoMotivoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoMotivoFocusGained

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCancelarActionPerformed

    // Constructor adicional para recibir fecha, hora y el controlador
public VistaFormulario(java.time.LocalDate fecha, String hora, Controlador.ListaController controller) {
     // 🟢 Llama directamente a la inicialización de los componentes
    initComponents(); 
    
    // Llama al constructor vacío para inicializar los componentes
    // Si querés mostrar la fecha y hora en el formulario, podés hacerlo así:
    setTitle("Formulario - Turno del " + fecha + " a las " + hora);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaFormulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JTextField CampoApellido;
    private javax.swing.JTextField CampoDNI;
    private java.awt.TextArea CampoMotivo;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoObraSocial;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBotonAtras() { // <-- CORRECCIÓN AQUÍ
    return BotonAtras;
}

public javax.swing.JButton getBotonCancelar() { // <-- CORRECCIÓN AQUÍ
    return BotonCancelar;
}

public javax.swing.JButton getBotonGuardar() { // <-- CORRECCIÓN AQUÍ
    return BotonGuardar;
}

    public javax.swing.JTextField getCampoNombre() {
        return  CampoNombre;
    }

    public javax.swing.JTextField getCampoApellido() {
        return  CampoApellido;
    }

    public javax.swing.JTextField getCampoDNI() {
return  CampoDNI;
    }

    public javax.swing.JTextField getCampoTelefono() {
        return  CampoTelefono;
    }

    public javax.swing.JTextField getCampoObraSocial() {
        return CampoObraSocial;
    }

   public TextArea getCampoMotivo() {
    return CampoMotivo; // Asumiendo que tu variable es JTextArea
}

    private void precargarDatos(Turno0 turno) {
    // 1. Manejar el Nombre y Apellido (asumiendo que están unidos por un espacio)
    String nombreCompleto = turno.getNombre();
    String[] partes = nombreCompleto.split(" ", 2); // Divide Nombre y Apellido

    // Asegúrate de que tus Getters (getCampoNombre, etc.) devuelvan el tipo correcto (JTextField/JTextArea)
    
    // Precarga el Nombre
    getCampoNombre().setText(partes[0]);
    
    // Precarga el Apellido (si existe una segunda parte)
    if (partes.length > 1) {
        getCampoApellido().setText(partes[1]);
    } else {
        getCampoApellido().setText(""); 
    }

    // 2. Precargar el resto de los campos
    getCampoDNI().setText(turno.getDni());
    getCampoTelefono().setText(turno.getTelefono());
    getCampoObraSocial().setText(turno.getObraSocial());
    getCampoMotivo().setText(turno.getMotivo()); // Si este es un JTextArea, funcionará bien.
    
    // 3. Opcional: Deshabilitar los campos de Fecha/Hora si la modificación no los permite
    // getCampoFecha().setEnabled(false);
    // getCampoHora().setEnabled(false);
}
}
