package Vista;

import Modelo.Turno0;
import Modelo.TurnoManager;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import Controlador.ListaController;

public class VistaListaDeTurnos extends javax.swing.JFrame {
    private ListaController controller; 

    public VistaListaDeTurnos() {
        initComponents();
        
        // 1. Instanciar el Controller. Pasa 'this' para que el controlador pueda interactuar.
        this.controller = new ListaController(this);
        
                
        
        fechaActual = LocalDate.now();
        jLabel1.setText("Turnos del día - " + fechaActual.format(formatoFecha));
        System.out.println("Turnos del dia - " + fechaActual.format(DateTimeFormatter.ofPattern("dd/MM")));
        // --- personalización visual de la tabla ---
        TablaTurnos.setColumnHeader(null);


        // Aplicar renderer personalizado para colorear (versión inline)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                Component cell = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);


                String nombre = (String) table.getValueAt(row, 1);

                if (nombre != null && nombre.equalsIgnoreCase("Libre")) {
                    cell.setBackground(new Color(220, 240, 220));
                    cell.setForeground(new Color(100, 100, 100));
                } else {
                    cell.setBackground(new Color(239, 239, 232));
                    cell.setForeground(new Color(21, 70, 77));
                }

                setHorizontalAlignment(JLabel.CENTER);
                return cell;
            }
        };

        for (int i = 0; i < 3; i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Configurar botones en la columna Acciones
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new RenderBotones());
 jTable1.getColumnModel().getColumn(3).setCellEditor(
    new Vista.EditorBotones(new JCheckBox(), jTable1, fechaActual, this.controller)
);

        // Ajustar ancho de columnas
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(350);

        // Ajustar altura de filas
        jTable1.setRowHeight(40);

        jTable1.setTableHeader(null);
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", java.awt.Font.PLAIN, 18));
        jTable1.setGridColor(new java.awt.Color(180, 214, 197));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);

        // --- Cargar horarios predefinidos ---
        cargarHorariosDelDia();

        // --- centrado y visibilidad ---
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setVisible(true);
    }



// NUEVO MÉTODO - Cargar horarios del día
    private void cargarHorariosDelDia() {
    javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);
    
    // Cargar turnos de la fecha actual desde TurnoManager
    for (Turno0 turno : TurnoManager.getInstancia().getTurnosPorFecha(fechaActual)) {
        modelo.addRow(new Object[]{
            turno.getHora(),
          //  turno.getNombre(),
            turno.getMotivo(),
            ""
        });
    }
}
    
  private void actualizarFechaYTurnos() {
    // 1. Actualizar título con la fecha
    jLabel1.setText("Turnos del día - " + fechaActual.format(formatoFecha));
    
    // 2. Actualizar el editor con la nueva fecha
    jTable1.getColumnModel().getColumn(3).setCellEditor( // Usa jTable1 directamente
        new EditorBotones(new JCheckBox(), jTable1, fechaActual, this.controller) // Usa this.controller
    );
    
    // 3. Recargar turnos
    cargarHorariosDelDia();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
  */   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        BotonDiaAnterio = new javax.swing.JButton();
        BotonDiaSiguiente = new javax.swing.JButton();

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TablaTurnos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 70, 77));

        jPanel2.setBackground(new java.awt.Color(239, 239, 232));


        BotonDiaAnterio.setBackground(new java.awt.Color(21, 70, 77));
        BotonDiaAnterio.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        BotonDiaAnterio.setText("Día anterior");
        BotonDiaAnterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             //iefioefionwo
            }
        });

        BotonDiaSiguiente.setBackground(new java.awt.Color(21, 70, 77));
        BotonDiaSiguiente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        BotonDiaSiguiente.setText("Día siguiente");
        BotonDiaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDiaSiguienteActionPerformed(evt);

            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 70, 77));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Turnos del día");
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 50));

        jSeparator1.setBackground(new java.awt.Color(21, 70, 77));
        jSeparator1.setForeground(new java.awt.Color(21, 70, 77));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 70, 77));
        jLabel2.setText("Hora");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 70, 77));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 70, 77));
        jLabel4.setText("Motivo");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 70, 77));
        jLabel5.setText("Acciones");

        TablaTurnos.setBackground(new java.awt.Color(239, 239, 232));
        TablaTurnos.setForeground(new java.awt.Color(239, 239, 232));

        jTable1.setBackground(new java.awt.Color(239, 239, 232));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaTurnos.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel2)
                .addGap(215, 215, 215)
                .addComponent(jLabel3)
                .addGap(295, 295, 295)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(273, 273, 273))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TablaTurnos)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()

                        .addComponent(BotonDiaAnterio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293)
                        .addComponent(BotonDiaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))

                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                            .addComponent(BotonDiaSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonDiaAnterio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))

                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)

                .addComponent(TablaTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))

        );

        jButton3.setBackground(new java.awt.Color(180, 214, 197));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Agendar turno");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.abrirFormularioTurno(fechaActual, "Nuevo");
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(626, 626, 626)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*

    */private void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
controller.diaAnterior();
    }
    private void BotonDiaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDiaSiguienteActionPerformed
        controller.diaSiguiente(); // Llamar al Controller
    }//GEN-LAST:event_BotonDiaSiguienteActionPerformed

    private void BotonDiaAnterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDiaAnterioActionPerformed
        controller.diaAnterior();
    }//GEN-LAST:event_BotonDiaAnterioActionPerformed


    /**
     * @param args the command line arguments
    */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
      */   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaListaDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaListaDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaListaDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaListaDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaListaDeTurnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton BotonDiaAnterio;
    private javax.swing.JButton BotonDiaSiguiente;
    private javax.swing.JScrollPane TablaTurnos;

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables

    private LocalDate fechaActual;
    private final DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    

public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }
}
